{
 "title": "Hyperf",
 "description": "🚀A coroutine framework that focuses on hyperspeed and flexibility. Building microservice or middleware with ease. https://www.hyperf.io",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "app_name", "query": "${VAR_APP_NAME}" },
   {
    "name": "instance",
    "query": "label_values([[app_name]]_connection_num,instance)"
   },
   {
    "name": "worker",
    "query": "label_values([[app_name]]_memory_usage,worker)"
   },
   {
    "name": "pool",
    "query": "label_values([[app_name]]_mysql_connections_in_use,pool)"
   },
   {
    "name": "path",
    "label": "path",
    "query": "label_values([[app_name]]_http_requests_count,request_path)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System Load",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg([[app_name]]_sys_load{instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum([[app_name]]_memory_usage{instance=~'$instance',worker=~'$worker'})"
    }
   ]
  },
  {
   "title": "Memory Peak Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum([[app_name]]_memory_peak_usage{instance=~'$instance',worker=~'$worker'})"
    }
   ]
  },
  {
   "title": "Current Event Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum([[app_name]]_event_num{instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "Current Coroutine Nums",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum([[app_name]]_coroutine_num{instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "Connection Nums",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum([[app_name]]_connection_num{instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "Accept Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum([[app_name]]_accept_count{instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "Current Tasking Nums",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum([[app_name]]_tasking_num{instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "Signal Listener Nums",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum([[app_name]]_signal_listener_num{instance=~'$instance',worker=~'$worker'})"
    }
   ]
  },
  {
   "title": "Current Timer Nums",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum([[app_name]]_timer_num{instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "Close Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum([[app_name]]_close_count{instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "Request Path Overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "round(sum(irate([[app_name]]_http_requests_count{instance=~\"$instance\"}[5m])) by (request_path), 0.001)"
    },
    {
     "expr": "round(sum(irate([[app_name]]_http_requests_count{instance=~\"$instance\",request_status=~\"[4-5].*\"}[5m])) by (request_path), 0.001)"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate([[app_name]]_http_requests_bucket{instance=~\"$instance\"}[5m])) by (le, request_path))",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate([[app_name]]_http_requests_bucket{instance=~\"$instance\"}[5m])) by (le, request_path))",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate([[app_name]]_http_requests_bucket{instance=~\"$instance\"}[5m])) by (le, request_path))",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "sum(rate([[app_name]]_http_requests_count{instance=~\"$instance\",request_status=~\"[1-3]\\\\d{2}\"}[5m]))  by (request_path)/sum(rate([[app_name]]_http_requests_count{instance=~\"$instance\",request_status=~\"[1-3]\\\\d{2}\"}[5m])) by (request_path)"
    }
   ]
  },
  { "title": "IO Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "MySQL Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum([[app_name]]_mysql_connections_in_use{instance=~'$instance', worker=~'$worker', pool=~'$pool'})",
     "legendFormat": "using"
    },
    {
     "expr": "sum([[app_name]]_mysql_connections_in_waiting{instance=~'$instance', worker=~'$worker', pool=~'$pool'})",
     "legendFormat": "waiting"
    },
    {
     "expr": "sum([[app_name]]_mysql_max_connections{instance=~'$instance', worker=~'$worker', pool=~'$pool'})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Redis Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum([[app_name]]_redis_connections_in_use{instance=~'$instance', worker=~'$worker', pool=~'$pool'})",
     "legendFormat": "using"
    },
    {
     "expr": "sum([[app_name]]_redis_connections_in_waiting{instance=~'$instance', worker=~'$worker', pool=~'$pool'})",
     "legendFormat": "waiting"
    },
    {
     "expr": "sum([[app_name]]_redis_max_connections{instance=~'$instance', worker=~'$worker', pool=~'$pool'})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Async Queue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum([[app_name]]_queue_waiting{instance=~'$instance',queue=~'default'})",
     "legendFormat": "waiting"
    },
    {
     "expr": "sum([[app_name]]_queue_delayed{instance=~'$instance',queue=~'default'})",
     "legendFormat": "delayed"
    },
    {
     "expr": "sum([[app_name]]_queue_failed{instance=~'$instance',queue=~'default'})",
     "legendFormat": "failed"
    },
    {
     "expr": "sum([[app_name]]_queue_timeout{instance=~'$instance',queue=~'default'})",
     "legendFormat": "timeout"
    }
   ]
  },
  { "title": "Runtime Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "System Load By Instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg([[app_name]]_sys_load{instance=~'$instance'}) by (instance)"
    }
   ]
  },
  {
   "title": "Memory By Instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum([[app_name]]_memory_usage) by (instance)"
    }
   ]
  },
  {
   "title": "Worker Stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum([[app_name]]_worker_request_count{instance=~'$instance',worker=~'$worker'})",
     "legendFormat": "request count"
    },
    {
     "expr": "sum([[app_name]]_worker_dispatch_count{instance=~'$instance',worker=~'$worker'})",
     "legendFormat": "dispatch count"
    },
    {
     "expr": "sum([[app_name]]_worker_num{instance=~'$instance',worker=~'$worker'})",
     "legendFormat": "worker num"
    },
    {
     "expr": "sum([[app_name]]_idle_worker_num{instance=~'$instance',worker=~'$worker'})",
     "legendFormat": "idle worker num"
    }
   ]
  },
  {
   "title": "GC Stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum([[app_name]]_gc_collected{instance=~'$instance', worker=~'$worker'})",
     "legendFormat": "collected"
    },
    {
     "expr": "sum([[app_name]]_gc_roots{instance=~'$instance', worker=~'$worker'})",
     "legendFormat": "roots"
    },
    {
     "expr": "sum([[app_name]]_gc_runs{instance=~'$instance', worker=~'$worker'})",
     "legendFormat": "runs"
    },
    {
     "expr": "sum([[app_name]]_gc_threshold{instance=~'$instance', worker=~'$worker'})",
     "legendFormat": "threshold"
    }
   ]
  },
  { "title": "Request Path Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 }, "repeat": "path" },
  {
   "title": "[[path]] Success Rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 51 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate([[app_name]]_http_requests_count{request_path=~\"$path\",request_status=~\"[1-3]\\\\d{2}\"}[5m])) / sum(rate([[app_name]]_http_requests_count{request_path=~\"$path\"}[5m]))*100"
    }
   ]
  },
  {
   "title": "[[path]] Latency Detail",
   "type": "graph",
   "gridPos": { "h": 11, "w": 19, "x": 5, "y": 51 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate([[app_name]]_http_requests_bucket{request_path=~'$path'}[15m])) by (le))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate([[app_name]]_http_requests_bucket{request_path=~'$path'}[15m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate([[app_name]]_http_requests_bucket{request_path=~'$path'}[15m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "[[path]] QPS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 54 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate([[app_name]]_http_requests_count{request_path=~'$path'}[5m]))"
    }
   ]
  },
  {
   "title": "[[path]] Average Latency",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 58 },
   "format": "dtdurations",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg([[app_name]]_http_requests_sum{request_path=~'$path'}/[[app_name]]_http_requests_count{request_path=~'$path'})"
    }
   ]
  }
 ]
}